spring:
  security:
    oauth2:
      client:
        registration:
          my-oauth2-client:
            provider: Google
            client-id:
            client-secret: 
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            scope: openid,profile,message.read,message.write
        provider:
          my-auth-server:
            issuer-uri: https://my-auth-server.com